# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: Build image
  jobs:
  - job: Job1
    displayName: Build_and_Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/MvcApp/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        dockerfile: '$(Build.SourcesDirectory)/MvcApp/Dockerfile'
        tags: |
          $(tag)
