apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mvc-app
    spec:
      containers:
      - image: 9767264150/products-store-mvc:v1.0
        name: mvc
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__ProductsContext
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: db-connection-string-secret 
            # configMapKeyRef:
            #   name: mssql-connnection-configmap
            #   key: db-connection-string 
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    
